# site settings
title: Roger's Portfolio
subtitle: 
email: roger.ferran.aranguren@gmail.com
description: Welcome to my personal portfolio<br/>
#baseurl: "/rferran.github.io" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Barcelona
state: 
zip_code:
country: Spain
phone: Ask for on the email.

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url:
github_url: https://github.com/rferran
gitlab_url: https://gitlab.com/rferran
googleplus_url: 
instagram_url: https://instagram.com/roogeer
linkedin_url: https://www.linkedin.com/in/rogerferran
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown
remote_theme: forty-jekyll-theme

sass:
  style: compressed
